name: salarybox
description: A new Flutter application.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get:
  get_storage:
  cached_network_image:
  url_launcher:
  collection:
  intl:
  flutter_launcher_icons:
  json_annotation:
  pinput:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Quicksand Bold
      fonts:
        - asset: assets/fonts/quicksand_bold.otf

    - family: Quicksand Medium
      fonts:
        - asset: assets/fonts/quicksand_medium.ttf

    - family: Quicksand Regular
      fonts:
        - asset: assets/fonts/quicksand_regular.otf
